# Generated by Django 3.2 on 2023-06-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='True if user is admin', verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
    ]
