# Generated by Django 3.2 on 2023-06-28 17:37

import django.core.validators
from django.db import migrations, models
import reviews.utils


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230627_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10, message='Введите число от 1 до 10.'), django.core.validators.MinValueValidator(limit_value=1, message='Введите число от 1 до 10.')], verbose_name='Оценка пользователя'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(reviews.utils.get_current_year)], verbose_name='Год выпуска'),
        ),
    ]
